<!doctype html>

<html>
<head>
  <title>Pho For All - Find Pho Fast!</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Noto+Sans">
  <link rel="stylesheet" href="./style.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
  <script src="./index.js"></script>
  <script src="./jquery.touchSwipe.min.js"></script>
  <script>$(document).ready(setupMobileMenu)</script>
</head>
<body>
  <div class="header">
    <h1 class="menu-button mobile">&#9776;</h1>
    <a class="logo" href="./">
      <h1>Pho For All</h1>
    </a>
  </div>
  <div class="wrapper">
    <div class="sidebar">
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed fermentum turpis diam, vitae pharetra lacus egestas a. Nam blandit purus in turpis eleifend, vel aliquet nisi tincidunt. Nam at justo euismod, aliquet ligula sit amet, accumsan diam. Nulla tincidunt elementum odio nec commodo. Nunc imperdiet dui arcu, ac pretium elit condimentum quis. Etiam mollis leo sed ligula consequat tristique. Sed ultrices rutrum tellus. Etiam ac ornare dui, non tincidunt quam. Praesent iaculis a ante ac faucibus. Pellentesque accumsan condimentum mollis. Integer ac mi et elit bibendum dictum vitae et risus. Vestibulum iaculis efficitur lorem sed suscipit. Maecenas lacus velit, lobortis ac posuere non, ultricies vel neque. Integer elementum nunc sit amet dui consectetur, euismod aliquet velit tristique.</p>
    </div>
    <div class="primary">
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed fermentum turpis diam, vitae pharetra lacus egestas a. Nam blandit purus in turpis eleifend, vel aliquet nisi tincidunt. Nam at justo euismod, aliquet ligula sit amet, accumsan diam. Nulla tincidunt elementum odio nec commodo. Nunc imperdiet dui arcu, ac pretium elit condimentum quis. Etiam mollis leo sed ligula consequat tristique. Sed ultrices rutrum tellus. Etiam ac ornare dui, non tincidunt quam. Praesent iaculis a ante ac faucibus. Pellentesque accumsan condimentum mollis. Integer ac mi et elit bibendum dictum vitae et risus. Vestibulum iaculis efficitur lorem sed suscipit. Maecenas lacus velit, lobortis ac posuere non, ultricies vel neque. Integer elementum nunc sit amet dui consectetur, euismod aliquet velit tristique.</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed fermentum turpis diam, vitae pharetra lacus egestas a. Nam blandit purus in turpis eleifend, vel aliquet nisi tincidunt. Nam at justo euismod, aliquet ligula sit amet, accumsan diam. Nulla tincidunt elementum odio nec commodo. Nunc imperdiet dui arcu, ac pretium elit condimentum quis. Etiam mollis leo sed ligula consequat tristique. Sed ultrices rutrum tellus. Etiam ac ornare dui, non tincidunt quam. Praesent iaculis a ante ac faucibus. Pellentesque accumsan condimentum mollis. Integer ac mi et elit bibendum dictum vitae et risus. Vestibulum iaculis efficitur lorem sed suscipit. Maecenas lacus velit, lobortis ac posuere non, ultricies vel neque. Integer elementum nunc sit amet dui consectetur, euismod aliquet velit tristique.</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed fermentum turpis diam, vitae pharetra lacus egestas a. Nam blandit purus in turpis eleifend, vel aliquet nisi tincidunt. Nam at justo euismod, aliquet ligula sit amet, accumsan diam. Nulla tincidunt elementum odio nec commodo. Nunc imperdiet dui arcu, ac pretium elit condimentum quis. Etiam mollis leo sed ligula consequat tristique. Sed ultrices rutrum tellus. Etiam ac ornare dui, non tincidunt quam. Praesent iaculis a ante ac faucibus. Pellentesque accumsan condimentum mollis. Integer ac mi et elit bibendum dictum vitae et risus. Vestibulum iaculis efficitur lorem sed suscipit. Maecenas lacus velit, lobortis ac posuere non, ultricies vel neque. Integer elementum nunc sit amet dui consectetur, euismod aliquet velit tristique.</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed fermentum turpis diam, vitae pharetra lacus egestas a. Nam blandit purus in turpis eleifend, vel aliquet nisi tincidunt. Nam at justo euismod, aliquet ligula sit amet, accumsan diam. Nulla tincidunt elementum odio nec commodo. Nunc imperdiet dui arcu, ac pretium elit condimentum quis. Etiam mollis leo sed ligula consequat tristique. Sed ultrices rutrum tellus. Etiam ac ornare dui, non tincidunt quam. Praesent iaculis a ante ac faucibus. Pellentesque accumsan condimentum mollis. Integer ac mi et elit bibendum dictum vitae et risus. Vestibulum iaculis efficitur lorem sed suscipit. Maecenas lacus velit, lobortis ac posuere non, ultricies vel neque. Integer elementum nunc sit amet dui consectetur, euismod aliquet velit tristique.</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed fermentum turpis diam, vitae pharetra lacus egestas a. Nam blandit purus in turpis eleifend, vel aliquet nisi tincidunt. Nam at justo euismod, aliquet ligula sit amet, accumsan diam. Nulla tincidunt elementum odio nec commodo. Nunc imperdiet dui arcu, ac pretium elit condimentum quis. Etiam mollis leo sed ligula consequat tristique. Sed ultrices rutrum tellus. Etiam ac ornare dui, non tincidunt quam. Praesent iaculis a ante ac faucibus. Pellentesque accumsan condimentum mollis. Integer ac mi et elit bibendum dictum vitae et risus. Vestibulum iaculis efficitur lorem sed suscipit. Maecenas lacus velit, lobortis ac posuere non, ultricies vel neque. Integer elementum nunc sit amet dui consectetur, euismod aliquet velit tristique.</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed fermentum turpis diam, vitae pharetra lacus egestas a. Nam blandit purus in turpis eleifend, vel aliquet nisi tincidunt. Nam at justo euismod, aliquet ligula sit amet, accumsan diam. Nulla tincidunt elementum odio nec commodo. Nunc imperdiet dui arcu, ac pretium elit condimentum quis. Etiam mollis leo sed ligula consequat tristique. Sed ultrices rutrum tellus. Etiam ac ornare dui, non tincidunt quam. Praesent iaculis a ante ac faucibus. Pellentesque accumsan condimentum mollis. Integer ac mi et elit bibendum dictum vitae et risus. Vestibulum iaculis efficitur lorem sed suscipit. Maecenas lacus velit, lobortis ac posuere non, ultricies vel neque. Integer elementum nunc sit amet dui consectetur, euismod aliquet velit tristique.</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed fermentum turpis diam, vitae pharetra lacus egestas a. Nam blandit purus in turpis eleifend, vel aliquet nisi tincidunt. Nam at justo euismod, aliquet ligula sit amet, accumsan diam. Nulla tincidunt elementum odio nec commodo. Nunc imperdiet dui arcu, ac pretium elit condimentum quis. Etiam mollis leo sed ligula consequat tristique. Sed ultrices rutrum tellus. Etiam ac ornare dui, non tincidunt quam. Praesent iaculis a ante ac faucibus. Pellentesque accumsan condimentum mollis. Integer ac mi et elit bibendum dictum vitae et risus. Vestibulum iaculis efficitur lorem sed suscipit. Maecenas lacus velit, lobortis ac posuere non, ultricies vel neque. Integer elementum nunc sit amet dui consectetur, euismod aliquet velit tristique.</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed fermentum turpis diam, vitae pharetra lacus egestas a. Nam blandit purus in turpis eleifend, vel aliquet nisi tincidunt. Nam at justo euismod, aliquet ligula sit amet, accumsan diam. Nulla tincidunt elementum odio nec commodo. Nunc imperdiet dui arcu, ac pretium elit condimentum quis. Etiam mollis leo sed ligula consequat tristique. Sed ultrices rutrum tellus. Etiam ac ornare dui, non tincidunt quam. Praesent iaculis a ante ac faucibus. Pellentesque accumsan condimentum mollis. Integer ac mi et elit bibendum dictum vitae et risus. Vestibulum iaculis efficitur lorem sed suscipit. Maecenas lacus velit, lobortis ac posuere non, ultricies vel neque. Integer elementum nunc sit amet dui consectetur, euismod aliquet velit tristique.</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed fermentum turpis diam, vitae pharetra lacus egestas a. Nam blandit purus in turpis eleifend, vel aliquet nisi tincidunt. Nam at justo euismod, aliquet ligula sit amet, accumsan diam. Nulla tincidunt elementum odio nec commodo. Nunc imperdiet dui arcu, ac pretium elit condimentum quis. Etiam mollis leo sed ligula consequat tristique. Sed ultrices rutrum tellus. Etiam ac ornare dui, non tincidunt quam. Praesent iaculis a ante ac faucibus. Pellentesque accumsan condimentum mollis. Integer ac mi et elit bibendum dictum vitae et risus. Vestibulum iaculis efficitur lorem sed suscipit. Maecenas lacus velit, lobortis ac posuere non, ultricies vel neque. Integer elementum nunc sit amet dui consectetur, euismod aliquet velit tristique.</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed fermentum turpis diam, vitae pharetra lacus egestas a. Nam blandit purus in turpis eleifend, vel aliquet nisi tincidunt. Nam at justo euismod, aliquet ligula sit amet, accumsan diam. Nulla tincidunt elementum odio nec commodo. Nunc imperdiet dui arcu, ac pretium elit condimentum quis. Etiam mollis leo sed ligula consequat tristique. Sed ultrices rutrum tellus. Etiam ac ornare dui, non tincidunt quam. Praesent iaculis a ante ac faucibus. Pellentesque accumsan condimentum mollis. Integer ac mi et elit bibendum dictum vitae et risus. Vestibulum iaculis efficitur lorem sed suscipit. Maecenas lacus velit, lobortis ac posuere non, ultricies vel neque. Integer elementum nunc sit amet dui consectetur, euismod aliquet velit tristique.</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed fermentum turpis diam, vitae pharetra lacus egestas a. Nam blandit purus in turpis eleifend, vel aliquet nisi tincidunt. Nam at justo euismod, aliquet ligula sit amet, accumsan diam. Nulla tincidunt elementum odio nec commodo. Nunc imperdiet dui arcu, ac pretium elit condimentum quis. Etiam mollis leo sed ligula consequat tristique. Sed ultrices rutrum tellus. Etiam ac ornare dui, non tincidunt quam. Praesent iaculis a ante ac faucibus. Pellentesque accumsan condimentum mollis. Integer ac mi et elit bibendum dictum vitae et risus. Vestibulum iaculis efficitur lorem sed suscipit. Maecenas lacus velit, lobortis ac posuere non, ultricies vel neque. Integer elementum nunc sit amet dui consectetur, euismod aliquet velit tristique.</p>
    </div>
  </div>
  <div class="swipe-area"></div>
</body>
</html>
